export const CONNECTION_REQUESTED = "CHAT_CONNECTION_REQUESTED";
export const CONNECTION_SUCCEEDED = "CHAT_CONNECTION_SUCCEEDED";
export const CONNECTION_CLOSED = "CHAT_CONNECTION_CLOSED";
export const CONNECTION_FAILED = "CHAT_CONNECTION_FAILED";

export const MESSAGE_RECEIVED = "CHAT_MESSAGE_RECEIVED";
export const MESSAGE_SEND_REQUEST = "MESSAGE_SEND_REQUEST";
